package com.mindlink.admin;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.mindlink.model.Student;
import com.mindlink.service.StudentService;

@Controller
@RequestMapping("/admin/user-management")
public class UserManagementController {

    @Autowired
    private StudentService studentService;

    // Main user management dashboard - redirect to students list
    @GetMapping
    public String index() {
        return "redirect:/admin/user-management/students";
    }

    // ========== STUDENT MANAGEMENT ==========

    // List all students
    @GetMapping("/students")
    public String listStudents(Model model) {
        List<Student> students = studentService.getAllStudents();
        model.addAttribute("students", students);
        return "admin/user-management/student-list";
    }

    // Show form for new student
    @GetMapping("/students/new")
    public String showNewStudentForm(Model model) {
        model.addAttribute("student", new Student());
        return "admin/user-management/student-form";
    }

    // Show form for editing student
    @GetMapping("/students/edit/{id}")
    public String showEditStudentForm(@PathVariable String id, Model model, RedirectAttributes redirectAttributes) {
        return studentService.getStudentById(id)
                .map(student -> {
                    model.addAttribute("student", student);
                    return "admin/user-management/student-form";
                })
                .orElseGet(() -> {
                    redirectAttributes.addFlashAttribute("error", "Student not found");
                    return "redirect:/admin/user-management/students";
                });
    }

    // Save or update student
    @PostMapping("/students/save")
    public String saveStudent(@ModelAttribute Student student, RedirectAttributes redirectAttributes) {
        try {
            // Set timestamps
            if (student.getStudentId() == null || student.getStudentId().isEmpty()) {
                // New student - will be generated by service
                student.setCreatedAt(LocalDateTime.now());
            } else {
                // Existing student - preserve created_at, set updated_at
                studentService.getStudentById(student.getStudentId())
                        .ifPresent(existing -> student.setCreatedAt(existing.getCreatedAt()));
            }
            student.setUpdatedAt(LocalDateTime.now());

            studentService.saveStudent(student);
            redirectAttributes.addFlashAttribute("success",
                    student.getStudentId() != null && !student.getStudentId().isEmpty()
                            ? "Student updated successfully"
                            : "Student created successfully");
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", "Error saving student: " + e.getMessage());
        }
        return "redirect:/admin/user-management/students";
    }

    // Delete student
    @GetMapping("/students/delete/{id}")
    public String deleteStudent(@PathVariable String id, RedirectAttributes redirectAttributes) {
        try {
            studentService.deleteStudent(id);
            redirectAttributes.addFlashAttribute("success", "Student deleted successfully");
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", "Error deleting student: " + e.getMessage());
        }
        return "redirect:/admin/user-management/students";
    }
}



